let obj = [ 
    "Select the entire array",
    "Split the selected array (as evenly as possible)" ,
    "Select the left subarray",
    'Split the selected array (as evenly as possible)' ,
    "Select the left subarray",
    "Split the selected array (as evenly as possible) ",
    "Select the left subarray",
    "Split the selected array (as evenly as possible) ",
    "An array of length 1 cannot be split, ready for merge",
    "An array of length 1 cannot be split, ready for merge",
    "Merge selected arrays back together, in sorted order",
    "Select the minimum of the two values",
    "Add the selected value to the sorted array",
    "When one list becomes empty, copy all values from the remaining array into the sorted array",
    "Add the selected value to the sorted array",
    "Finished merging",
    'An array of length 1 cannot be split, ready for merge',
    'Merge selected arrays back together, in sorted order' ,
    "Select the smallest value from the front of each list (excluding values already in the sorted array)",
    "Select the minimum of the two values",
    "Add the selected value to the sorted array",
    "Select the smallest value from the front of each list (excluding values already in the sorted array)",
    "Select the minimum of the two values",
    "Add the selected value to the sorted array ",
    "When one list becomes empty, copy all values from the remaining array into the sorted array",
    "Add the selected value to the sorted array",
    "Finished merging",
    "Select the right subarray",
    "Split the selected array (as evenly as possible)",
    "An array of length 1 cannot be split, ready for merge",
    "An array of length 1 cannot be split, ready for merge",
    "Merge selected arrays back together, in sorted order",
    "Select the minimum of the two values",
    "Add the selected value to the sorted array",
    "When one list becomes empty, copy all values from the remaining array into the sorted array",
    "Add the selected value to the sorted array",
    "Finished merging",
    "Merge selected arrays back together, in sorted order",
    "Select the smallest value from the front of each list (excluding values already in the sorted array)",
    "Select the minimum of the two values",
    "Add the selected value to the sorted array",
    "Select the smallest value from the front of each list (excluding values already in the sorted array)",
    "Select the minimum of the two values",
    "Add the selected value to the sorted array",
    "Select the smallest value from the front of each list (excluding values already in the sorted array)",
    "Select the minimum of the two values",
    "Add the selected value to the sorted array",
    "When one list becomes empty, copy all values from the remaining array into the sorted array",
    "Add the selected value to the sorted array",
    "When one list becomes empty, copy all values from the remaining array into the sorted array",
    "Add the selected value to the sorted array",
    "Finished merging",
    "Select the right subarray",
    "Split the selected array (as evenly as possible)",
    "Select the left subarray",
    "Split the selected array (as evenly as possible)",
    "An array of length 1 cannot be split, ready for merge",
    "An array of length 1 cannot be split, ready for merge",
    "Merge selected arrays back together, in sorted order",
    "Select the minimum of the two values",
    "Add the selected value to the sorted array",
    "When one list becomes empty, copy all values from the remaining array into the sorted array",
    "Add the selected value to the sorted array",
    "Finished merging",
    "Select the right subarray",
    "Split the selected array (as evenly as possible)",
    "An array of length 1 cannot be split, ready for merge",
    "An array of length 1 cannot be split, ready for merge",
    "Merge selected arrays back together, in sorted order",
    "Add the selected value to the sorted array",
    "Finished merging",
    "Merge selected arrays back together, in sorted order",
    "Select the smallest value from the front of each list (excluding values already in the sorted array)",
    "Select the minimum of the two values ",
    "Add the selected value to the sorted array",
    "Select the smallest value from the front of each list (excluding values already in the sorted array)",
    "Select the minimum of the two values",
    "Add the selected value to the sorted array",
    "Select the smallest value from the front of each list (excluding values already in the sorted array)",
    "Select the minimum of the two values ",
    "Add the selected value to the sorted array",
    "When one list becomes empty, copy all values from the remaining array into the sorted array",
    "Add the selected value to the sorted array",
    "Finished merging",
    "Merge selected arrays back together, in sorted order",
    "Select the smallest value from the front of each list (excluding values already in the sorted array)",
    "Select the minimum of the two values ",
    "Add the selected value to the sorted array",
    "Select the smallest value from the front of each list (excluding values already in the sorted array)",
    "Select the minimum of the two values ",
    "Add the selected value to the sorted array",
    "Select the smallest value from the front of each list (excluding values already in the sorted array)",
    "Select the minimum of the two values ",
    "Add the selected value to the sorted array",
    "Select the smallest value from the front of each list (excluding values already in the sorted array)",
    "Select the minimum of the two values",
    "Add the selected value to the sorted array",
    "Select the smallest value from the front of each list (excluding values already in the sorted array)",
    "Select the minimum of the two values" ,
    "Add the selected value to the sorted array",
    "Select the smallest value from the front of each list (excluding values already in the sorted array)",
    "Select the minimum of the two values",
    "Add the selected value to the sorted array ",
    "Select the smallest value from the front of each list (excluding values already in the sorted array)",
    "Select the minimum of the two values ",
    "Add the selected value to the sorted array", 
    "When one list becomes empty, copy all values from the remaining array into the sorted array",
    "Add the selected value to the sorted array",
    "When one list becomes empty, copy all values from the remaining array into the sorted array",
    "Add the selected value to the sorted array",
    "Finished merging",
    "Done sorting! "
]